# Generated by Django 6.0.6 on 2026-06-07 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HabitLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время выполнения")),
                ("status", models.BooleanField(default=True, verbose_name="Статус выполнения")),
            ],
            options={
                "verbose_name": "Выполнение привычки",
                "verbose_name_plural": "Выполнения привычек",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(max_length=255, verbose_name="Действие")),
                ("time", models.TimeField(verbose_name="Время выполнения")),
                ("place", models.CharField(max_length=255, verbose_name="Место выполнения")),
                ("is_pleasant", models.BooleanField(default=False, verbose_name="Признак приятной привычки")),
                ("reward", models.CharField(blank=True, max_length=255, null=True, verbose_name="Вознаграждение")),
                ("periodicity", models.IntegerField(default=1, verbose_name="Периодичность (в днях)")),
                ("duration", models.IntegerField(default=2, verbose_name="Время на выполнение (мин)")),
                ("is_public", models.BooleanField(default=False, verbose_name="Публичный доступ")),
                (
                    "bound_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
        ),
    ]
